final/config/routes.rb
Rails.application.routes.draw do
	 get 'after_login/index'


  devise_for :users
    root to: "after_login#index"
	get 'after_login/index'
	put 'after_login/update'
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

final/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

final/app/models/stud.rb
class Stud < ApplicationRecord
end

final/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable
end

final/app/controllers/after_login_controller.rb
class AfterLoginController < ApplicationController
before_filter :authenticate_user!

	
  def index
  	  @studs = Stud.all
  	  params[:studs_appr]

  end

def update
	
 params[:stud].each {|key, value| Stud.find(key.to_i).update(appr: value[:appr].to_i) }
 redirect_to after_login_index_path

end
end

final/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

final/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

final/app/helpers/after_login_helper.rb
module AfterLoginHelper
end

final/app/helpers/application_helper.rb
module ApplicationHelper
end

final/app/helpers/home_helper.rb
module HomeHelper
end

final/app/views/after_login/index.html.erb
 <tbody>


<%= form_tag after_login_update_path,method: :put do %>

<% @studs.each do |studs| %>
<%= fields_for "stud[]", studs do |stud_fields| %>
 	 <tr>


      

 	    <% if studs and studs.facmail==current_user.email  %>
 	        <% if studs.id%40 == 6 %>
 	         <%if Stud.find(studs.id - 6).appr==1 %> 
 	          <div class="field">
               <%= stud_fields.check_box :appr %>
               <%= studs.studname %>
         	   </div>
         	 <%end%>
         	<%end%>

         	
         	<% if studs.id%40 == 7 %>
 	         <%if Stud.find(studs.id - 5).appr==1 %> 
 	          <div class="field">
               <%= stud_fields.check_box :appr %>
               <%= studs.studname %>
         	  </div>
         	 <%end%>
         	<%end%>
         	

         	<% if studs.id%40 == 8 %>
 	         <%if Stud.find(studs.id - 5).appr==1 %> 
 	          <div class="field">
               <%= stud_fields.check_box :appr %>
               <%= studs.studname %>
         	   </div>
         	 <%end%>
         	<%end%>

         	
         	<% if studs.id%40 == 9 %>
 	         <%if Stud.find(studs.id - 8).appr==1 and Stud.find(studs.id - 4).appr==1 %> 
 	          <div class="field">
               <%= stud_fields.check_box :appr %>
               <%= studs.studname %>
         	  </div>
         	 <%end%>
         	<%end%>
			
			
			<% if studs.id%40 == 10 %>
 	         <%if Stud.find(studs.id - 4).appr==1 and Stud.find(studs.id - 3).appr==1 and Stud.find(studs.id - 2).appr==1 and Stud.find(studs.id - 1).appr==1 and 
                Stud.find(studs.id - 6).appr==1 and Stud.find(studs.id + 2).appr==1  and Stud.find(studs.id + 3).appr==1  and
                Stud.find(studs.id + 4).appr==1  and Stud.find(studs.id + 5).appr==1  and Stud.find(studs.id + 6).appr==1  and Stud.find(studs.id + 7).appr==1  and 
                Stud.find(studs.id + 8).appr==1  and Stud.find(studs.id + 9).appr==1  and Stud.find(studs.id + 10).appr==1  and Stud.find(studs.id + 11).appr==1  and 
                Stud.find(studs.id + 12).appr==1  and Stud.find(studs.id + 13).appr==1  and Stud.find(studs.id + 14).appr==1  and Stud.find(studs.id + 15).appr==1  and
                Stud.find(studs.id + 16).appr==1  and Stud.find(studs.id + 17).appr==1  and Stud.find(studs.id + 18).appr==1  and Stud.find(studs.id + 19).appr==1  and 
                Stud.find(studs.id + 20).appr==1  and Stud.find(studs.id + 21).appr==1  and Stud.find(studs.id + 22).appr==1  and Stud.find(studs.id + 23).appr==1  and 
                Stud.find(studs.id + 24).appr==1  and Stud.find(studs.id + 25).appr==1  and Stud.find(studs.id + 26).appr==1  and Stud.find(studs.id + 27).appr==1   and 
                Stud.find(studs.id + 28).appr==1  and Stud.find(studs.id + 29).appr==1 %> 
 	          <div class="field">
               <%= stud_fields.check_box :appr %>
               <%= studs.studname %>
         	   </div>
         	 <%end%>
         	<%end%>

         	
         	<% if studs.id%40 == 11 %>
 	         <%if Stud.find(studs.id - 1).appr==1 %> 
 	          <div class="field">
               <%= stud_fields.check_box :appr %>
               <%= studs.studname %>
         	  </div>
         	 <%end%>
         	<%end%>

         
          <% if studs.id%40 <= 5 or studs.id%40 >= 12 %>       
 	         <div class="field">
              <%= stud_fields.check_box :appr %>
              <%= studs.studname %>
         	 </div>
         	<%end%>
         <% end %>
 
        <% if studs and studs.studmail==current_user.email %>
           <% if studs.appr==0 %>
         	 <div class="field">
             Not Approved by   <%= studs.facname %>
             </div>
           <%end%>
           <% if studs.appr==1 %>
             <div class="field">
         	   Approved by       <%= studs.facname %>
         	 </div>
           <%end%>

         
        <% end %>
 
         

   
   </tr>


<% end %>
<% end %>


 
  <div class="actions">
 <%= submit_tag "Save changes" %>
 </div>


<% end %>


</tbody>
 

final/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

final/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proj</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
       <%= link_to "Sign out", destroy_user_session_path,method: :delete %> <br>
    <% else %>
       <%= link_to "Sign in",  new_user_session_path %><br>
    <% end %>
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>